# actionlint configuration
# See: https://github.com/rhysd/actionlint/blob/main/docs/config.md

# Self-hosted runner labels (add if using self-hosted runners)
self-hosted-runner:
  labels: []

# Configuration variables defined in repository settings
# config-variables: []

# Paths to ignore certain errors (glob patterns)
# paths:
#   '.github/workflows/generated-*.yml':
#     ignore:
#       - 'SC2086'  # shellcheck: double quote warning
